### ISSUE TITLE
请问你是如何Patched的？

### ISSUE THREAD

**Issue by kinkenyuen** [xybp888/iOS-SDKs#1]
我使用[theos sdks](https://github.com/theos/sdks)的脚本配合tbd没法将私有库递归将mach-o批量转成.tbd,请教一下tbd命令你是怎么输入的？

**Comment by xybp888** [comment]
> 我使用[theos sdks](https://github.com/theos/sdks)的脚本配合tbd没法将私有库递归将mach-o批量转成.tbd,请教一下tbd命令你是怎么输入的？

你需要自行修改tbd,编译
