### ISSUE TITLE
how do i use one of these sdks?

### ISSUE THREAD

**Issue by JonnycatMeow** [xybp888/iOS-SDKs#10]
i have a macos Monterey and i currently have a 16.2 sdk   and i was wondering how do i use a 16.4 sdk instead of 16.2 sdk and yes i have xcode

**Comment by xybp888** [comment]
Update latest Xcode

**Comment by JonnycatMeow** [comment]
i have a intel macbook but my mac intel for my xcode does not support 16.4 and it does not support the newest macos update
