### ISSUE TITLE
Unknown key 'weak-def-symbols' for iOS 13.5

### ISSUE THREAD

**Issue by Not-Nik** [xybp888/iOS-SDKs#2]
I'm getting this when compiling for iOS 13.5. 13.4 works fine tho
```
ld: in '/Volumes/nikolas/theos/sdks/iPhoneOS13.5.sdk/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore.tbd', malformed file
/Volumes/nikolas/theos/sdks/iPhoneOS13.5.sdk/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore.tbd:17000:29: error: unknown key 'weak-def-symbols'
    weak-def-symbols:     [ __ZdlPv, __Znwm, _mig_strncpy_zerofill,
```

**Comment by eclair4151** [comment]
same here

**Comment by DarthShmev** [comment]
I too am having the same issue.

**Comment by alza54** [comment]
If iOS 13.5 SDK is broken how can we downgrade to 13.4.1 if it is not signed by Apple anymore?

**Comment by eclair4151** [comment]
Your comment is unrelated to this issue, but you cannot downgrade unless you saved your shsh blobs for your phone while that iOS was being signed

**Comment by xybp888** [comment]
Fixed, please download again
