### ISSUE TITLE
Using @available(iOS 13, *) throws Undefined symbols for architecture arm64:   "___isOSVersionAtLeast"

### ISSUE THREAD

**Issue by eclair4151** [xybp888/iOS-SDKs#3]
I'm trying to do this
`if (@available(iOS 13, *)) {
        navController.modalInPresentation = YES;
}`

But it throws this error. Any suggestions

`==> Linking bundle NotiBlockPref (arm64e)…
Undefined symbols for architecture arm64e:
  "___isOSVersionAtLeast", referenced from:
      -[NBPRootTableViewController addButtonTapped:] in NBPRootTableViewController.m.6173ed7d.o
ld: symbol(s) not found for architecture arm64e
Not signing file
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [/Development/theos/makefiles/instance/bundle.mk:37: /Development/notiblock/.theos/obj/debug/arm64e/NotiBlockPref.bundle/NotiBlockPref] Error 1
==> Linking bundle NotiBlockPref (arm64)…
Undefined symbols for architecture arm64:
  "___isOSVersionAtLeast", referenced from:
      -[NBPRootTableViewController addButtonTapped:] in NBPRootTableViewController.m.91275551.o
ld: symbol(s) not found for architecture arm64
Not signing file
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [/Development/theos/makefiles/instance/bundle.mk:37: /Development/notiblock/.theos/obj/debug/arm64/NotiBlockPref.bundle/NotiBlockPref] Error 1
make[3]: *** [/Development/theos/makefiles/instance/bundle.mk:37: /Development/notiblock/.theos/obj/debug/arm64e/NotiBlockPref.bundle/NotiBlockPref] Error 2
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [/Development/theos/makefiles/instance/bundle.mk:37: /Development/notiblock/.theos/obj/debug/arm64/NotiBlockPref.bundle/NotiBlockPref] Error 2
make[2]: *** [/Development/theos/makefiles/instance/bundle.mk:26: internal-bundle-all_] Error 2
make[1]: *** [/Development/theos/makefiles/master/rules.mk:111: NotiBlockPref.all.bundle.variables] Error 2
make: *** [/Development/theos/makefiles/master/aggregate.mk:12: internal-all] Error 2
Tomers-iPhone:/Development/notiblock root# 
`

**Comment by eclair4151** [comment]
i fixed this by adding this to the top of the file where needed

int __isOSVersionAtLeast(int major, int minor, int patch) { NSOperatingSystemVersion version; version.majorVersion = major; version.minorVersion = minor; version.patchVersion = patch; return [[NSProcessInfo processInfo] isOperatingSystemAtLeastVersion:version]; }

**Comment by badger200** [comment]
> int __isOSVersionAtLeast(int major, int minor, int patch) { NSOperatingSystemVersion version; version.majorVersion = major; version.minorVersion = minor; version.patchVersion = patch; return [[NSProcessInfo processInfo] isOperatingSystemAtLeastVersion:version]; }

Thanks a million, man. For some reason I’m getting this compiling Python 3.9.2 and I can’t find this isOSVersionAtLeast anywhere except in libswift modules and I don’t do anything with swift whatsoever. Tried every theos SDK from 9.3-14.0 even 12.4 which doesn’t even have this function. No idea where it’s coming from as it’s not in the Python source. But thanks I bet your fix will work!
