### ISSUE TITLE
zips/tars/releases

### ISSUE THREAD

**Issue by Diatrus** [xybp888/iOS-SDKs#5]
It would be useful if you provided compressed SDKs, in order to download them individually.

**Comment by ljhnhlh** [comment]
hi, I wonder how to find these sdk files, could you please tell me,thanks.

**Comment by IlannM** [comment]
> It would be useful if you provided compressed SDKs, in order to download them individually.

this. having to download them all when you just want one is pretty annoying. having them as tarballs would be nice.

**Comment by badger200** [comment]
> > It would be useful if you provided compressed SDKs, in order to download them individually.
> 
> this. having to download them all when you just want one is pretty annoying. having them as tarballs would be nice.

Check out THEOS, on bigboss “randy420” has “tai” (THEOS Auto Installer) that lets you check-off which (patched) SDKs you want, then installs them automatically via downloading ZIPs of each SDK, I’ve built a ton of projects successfully using it the past 2y.

**Comment by xybp888** [comment]
Add a zip version for easy download
