### ISSUE TITLE
iOS 16.4 SDK and Support Files

### ISSUE THREAD

**Issue by mizzyexists** [xybp888/iOS-SDKs#9]
I went ahead a ripped the latest iOS 16.4 SDK and Support files from the newest XCode. I've zipped and attached them to this issue for upload. Enjoy!

[iOS16.4.zip](https://github.com/xybp888/iOS-SDKs/files/10867279/iOS16.4.zip)

**Comment by xybp888** [comment]
This is an beta version and your file is not valid but thanks for sharing
